# Generated by Django 4.0.3 on 2022-03-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1500)),
                ('user', models.CharField(max_length=1500)),
            ],
        ),
    ]
